directive @upper on FIELD_DEFINITION
directive @lower on FIELD_DEFINITION

schema {
  query: Query
}

type Query {
  User: [User] @hasRole(role:["Admin","User"])
}

type User {
  user_id:ID
  first_name:String @upper
}
